on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2.0.0
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore -r win-x64

      - name: Get the tag name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Build
        shell: pwsh
        run: |
          # Variables
          $repository_name="${{ github.event.repository.name }}"
          $tag="${{ github.event.ref }}"
          $release_name="${repository_name}-${tag}"
          echo Building ${release_name}
          # Publish
          dotnet publish --no-restore --no-self-contained -r win-x64 -c Release -o "$release_name"
          pushd "${release_name}"
          # Zip the build
          7z a -tzip "..\${release_name}.zip" "*"
          # Go back
          popd
          # Delete output directory
          rm -r "$release_name"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "*.zip"
